name: Build playerctl

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          meson \
          ninja-build \
          pkg-config \
          libglib2.0-dev \
          gobject-introspection \
          libgirepository1.0-dev

    - name: Configure and build
      run: |
        meson build
        ninja -C build

    - name: Run tests
      run: |
        ninja -C build test