name: Build playerctl for ARM64

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          autoconf \
          automake \
          libtool \
          pkg-config \
          gcc-aarch64-linux-gnu \
          g++-aarch64-linux-gnu \
          libglib2.0-dev:arm64

    - name: Set up cross-compilation environment
      run: |
        export CC=aarch64-linux-gnu-gcc
        export CXX=aarch64-linux-gnu-g++
        export PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig

    - name: Generate build system
      run: |
        ./autogen.sh

    - name: Configure for ARM64
      run: |
        ./configure --host=aarch64-linux-gnu --prefix=/usr

    - name: Build playerctl
      run: |
        make

    - name: Archive build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: playerctl-arm64
        path: |
          playerctl
          playerctl-*.tar.gz