name: Build Playerctl for Armbian ARM644

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # 允许手动触发编译

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout playerctl source code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo dpkg --add-architecture arm64
          sudo apt update
          sudo apt install -y \
            gcc-aarch64-linux-gnu g++-aarch64-linux-gnu \
            meson ninja-build pkg-config \
            libglib2.0-dev:arm64 libgobject-2.0-dev:arm64 \
            gobject-introspection:arm64

      - name: Set up cross-compilation file
        run: |
          cat <<EOF > cross-file.txt
          [binaries]
          c = 'aarch64-linux-gnu-gcc'
          cpp = 'aarch64-linux-gnu-g++'
          ar = 'aarch64-linux-gnu-ar'
          strip = 'aarch64-linux-gnu-strip'
          pkgconfig = 'pkg-config'

          [host_machine]
          system = 'linux'
          cpu_family = 'aarch64'
          cpu = 'aarch64'
          endian = 'little'

          [paths]
          prefix = '/usr/aarch64-linux-gnu'
          libdir = '/usr/lib/aarch64-linux-gnu'
          bindir = '/usr/bin'
          includedir = '/usr/include'
          EOF

      - name: Build playerctl
        run: |
          meson setup builddir --cross-file cross-file.txt
          ninja -C builddir

      - name: Archive playerctl binary
        uses: actions/upload-artifact@v4
        with:
          name: playerctl-arm64
          path: builddir/playerctl
