name: Build Playerctl for ARM64

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          meson \
          ninja-build \
          pkg-config \
          gcc-aarch64-linux-gnu \
          g++-aarch64-linux-gnu \
          binutils-aarch64-linux-gnu \
          libglib2.0-dev \
          libglib2.0-dev-arm64-cross \
          gobject-introspection \
          libgirepository1.0-dev \
          gtk-doc-tools
        
    - name: Configure Build
      run: |
        mkdir -p builddir
        meson setup builddir \
          --cross-file cross_file.txt \
          -Dgtk-doc=false \
          -Dintrospection=false
      env:
        CC: aarch64-linux-gnu-gcc
        CXX: aarch64-linux-gnu-g++
        PKG_CONFIG_PATH: /usr/lib/aarch64-linux-gnu/pkgconfig
        
    - name: Create Cross File
      run: |
        cat > cross_file.txt <<EOF
        [binaries]
        c = 'aarch64-linux-gnu-gcc'
        cpp = 'aarch64-linux-gnu-g++'
        ar = 'aarch64-linux-gnu-ar'
        strip = 'aarch64-linux-gnu-strip'
        pkgconfig = 'pkg-config'

        [host_machine]
        system = 'linux'
        cpu_family = 'aarch64'
        cpu = 'aarch64'
        endian = 'little'
        EOF
        
    - name: Build
      run: ninja -C builddir
        
    - name: Create Package
      run: |
        cd builddir
        tar -czf playerctl-arm64.tar.gz playerctl
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: playerctl-arm64
        path: builddir/playerctl-arm64.tar.gz
