name: Build Playerctl ARM64

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: altdesktop/playerctl
          submodules: recursive
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build in ARM64 container
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          push: false
          load: true
          tags: playerctl-builder:latest
          file: Dockerfile
      
      - name: Copy artifacts
        run: |
          docker create --name temp playerctl-builder:latest
          docker cp temp:/usr/local/lib/libplayerctl.so ./
          docker cp temp:/usr/local/bin/playerctl ./
          docker rm temp
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: playerctl-arm64
          path: |
            ./libplayerctl.so
            ./playerctl
