- name: 安装 QEMU 并设置 `arm64` Ubuntu
  run: |
    sudo apt update
    sudo apt install -y qemu-user-static debootstrap binfmt-support

    # 创建 ARM64 根文件系统
    sudo debootstrap --arch=arm64 focal rootfs http://ports.ubuntu.com/

    # 复制 QEMU 到 `rootfs`
    sudo cp /usr/bin/qemu-aarch64-static rootfs/usr/bin/

- name: 进入 `arm64` Ubuntu 并安装依赖
  run: |
    sudo chroot rootfs /bin/bash -c "
      apt update &&
      apt install -y build-essential meson ninja-build
      apt install -y libglib2.0-dev libgobject-2.0-dev libgio-2.0-dev
      apt install -y libdbus-1-dev libjson-glib-dev libreadline-dev bash-completion
    "
