name: Build playerctl for Armbian

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 安装依赖
      run: |
        sudo apt update
        sudo apt install -y build-essential meson ninja-build \
                            libglib2.0-dev libjson-glib-dev \
                            libdbus-1-dev pkg-config \
                            gcc-aarch64-linux-gnu g++-aarch64-linux-gnu \
                            gobject-introspection libgirepository1.0-dev

    - name: 设置交叉编译环境
      run: |
        echo "[binaries]
        c = 'aarch64-linux-gnu-gcc'
        cpp = 'aarch64-linux-gnu-g++'
        ar = 'aarch64-linux-gnu-ar'
        strip = 'aarch64-linux-gnu-strip'
        pkg-config = '/usr/bin/pkg-config'

        [host_machine]
        system = 'linux'
        cpu_family = 'aarch64'
        cpu = 'armv8-a'
        endian = 'little'" > cross.txt

    - name: 编译 playerctl
      run: |
        meson setup --cross-file=cross.txt   -Dgtk-doc=false -Dintrospection=false build
        cd build
        ninja

    - name: 打包为 `.tar.gz`
      run: |
        tar -czvf playerctl-armbian.tar.gz -C build playerctl

    - name: 上传构建产物
      uses: actions/upload-artifact@v4
      with:
        name: playerctl-armbian
        path: playerctl-armbian.tar.gz
