name: Docker Build Playerctl for Armbian (Docker)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 在 `arm64` Docker 容器中编译
        run: |
          docker run --rm -v $(pwd):/workspace -w /workspace arm64v8/ubuntu bash -c "
            apt update &&
            apt install -y build-essential meson ninja-build &&
            apt install -y libglib2.0-dev libgobject-2.0-dev libgio-2.0-dev &&
            apt install -y libdbus-1-dev libjson-glib-dev libreadline-dev bash-completion &&
            meson setup build &&
            ninja -C build
          "
