name: Build Playerctl ARM64

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version tag to build (optional)'
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: altdesktop/playerctl
          submodules: recursive
          ref: ${{ github.event.inputs.tag }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build playerctl for ARM64
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/arm64
          push: false
          load: true
          tags: playerctl-arm64:latest
      
      - name: Extract build artifacts
        run: |
          # Create a container from the image
          container_id=$(docker create playerctl-arm64:latest)
          
          # Create directory for artifacts
          mkdir -p artifacts
          
          # Copy the built files from the container
          docker cp $container_id:/usr/lib/libplayerctl.so artifacts/
          docker cp $container_id:/usr/bin/playerctl artifacts/
          
          # Clean up container
          docker rm $container_id
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: playerctl-arm64-build
          path: artifacts/
          retention-days: 7

      - name: List artifacts
        run: |
          echo "Build artifacts:"
          ls -lah artifacts/
