name: Playerctl for ARM64

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        repository: 'altdesktop/playerctl'
        submodules: 'recursive'

    - name: Install dependencies
      run: |
        sudo dpkg --add-architecture arm64
        sudo apt-get update
        sudo apt-get install -y \
          gcc-aarch64-linux-gnu \
          g++-aarch64-linux-gnu \
          meson \
          ninja-build \
          pkg-config \
          libglib2.0-dev:arm64 \
          libgirepository1.0-dev:arm64 \
          libgio-2.0-0:arm64 \
          libgobject-2.0-0:arm64 \
          gobject-introspection \
          libtool

    - name: Set up cross-compilation environment
      run: |
        cat << EOF > cross-file.txt
        [binaries]
        c = 'aarch64-linux-gnu-gcc'
        cpp = 'aarch64-linux-gnu-g++'
        ar = 'aarch64-linux-gnu-ar'
        strip = 'aarch64-linux-gnu-strip'
        pkg-config = 'aarch64-linux-gnu-pkg-config'

        [properties]
        sys_root = '/usr/aarch64-linux-gnu'
        pkg_config_libdir = '/usr/lib/aarch64-linux-gnu/pkgconfig'

        [host_machine]
        system = 'linux'
        cpu_family = 'aarch64'
        cpu = 'armv8'
        endian = 'little'
        EOF

        # Create a wrapper for pkg-config to handle cross-compilation
        sudo tee /usr/bin/aarch64-linux-gnu-pkg-config << 'EOF' > /dev/null
        #!/bin/sh
        export PKG_CONFIG_PATH=
        export PKG_CONFIG_LIBDIR=/usr/lib/aarch64-linux-gnu/pkgconfig
        export PKG_CONFIG_SYSROOT_DIR=/usr/aarch64-linux-gnu
        exec pkg-config "$@"
        EOF
        sudo chmod +x /usr/bin/aarch64-linux-gnu-pkg-config

    - name: Configure build
      run: |
        meson setup builddir \
          --cross-file cross-file.txt \
          --prefix=/usr \
          -Dgtk-doc=false \
          -Dintrospection=false \
          --libdir=lib/aarch64-linux-gnu

    - name: Build
      run: ninja -C builddir

    - name: Create package
      run: |
        mkdir -p artifact/bin artifact/lib
        cp builddir/playerctl/playerctl artifact/bin/
        cp builddir/playerctl/playerctld artifact/bin/
        cp builddir/playerctl/libplayerctl.so* artifact/lib/
        strip artifact/bin/* artifact/lib/*
        tar czf playerctl-arm64.tar.gz -C artifact .

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: playerctl-arm64
        path: playerctl-arm64.tar.gz
