name: 2025 Build Playerctl ARM64

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version tag to build (optional)'
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: altdesktop/playerctl
          submodules: recursive
          ref: ${{ github.event.inputs.tag }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and run container
        run: |
          # Create Dockerfile
          cat > Dockerfile.arm64 << EOF
          FROM ubuntu:20.04
          
          ENV DEBIAN_FRONTEND=noninteractive
          
          # Install build dependencies
          RUN apt-get update && apt-get install -y --no-install-recommends \
              python3-pip \
              python3-setuptools \
              python3-wheel \
              ninja-build \
              build-essential \
              libglib2.0-dev \
              libgirepository1.0-dev \
              gtk-doc-tools \
              dbus-x11 \
              pkg-config \
              git \
              && rm -rf /var/lib/apt/lists/*
          
          # Install updated meson
          RUN pip3 install --no-cache-dir meson==0.56.0
          
          WORKDIR /app
          COPY . /app
          
          # Build playerctl
          RUN meson setup build \
              --prefix=/usr \
              --libdir=/usr/lib/aarch64-linux-gnu \
              -Dgtk-doc=false \
              && ninja -C build \
              && ninja -C build install \
              && ldconfig
          EOF
          
          # Build image
          docker buildx build \
            --platform linux/arm64 \
            --load \
            -f Dockerfile.arm64 \
            -t playerctl-arm64:latest \
            .
          
          # Create and start container
          docker run -d --platform linux/arm64 --name playerctl-build \
            playerctl-arm64:latest \
            sleep infinity
          
          # Create artifacts directory structure
          mkdir -p artifacts/playerctl/usr/{bin,lib/aarch64-linux-gnu}
          
          # Copy files
          docker cp playerctl-build:/usr/bin/playerctl artifacts/playerctl/usr/bin/
          docker cp playerctl-build:/usr/lib/aarch64-linux-gnu/libplayerctl.so.2.0.0 artifacts/playerctl/usr/lib/aarch64-linux-gnu/
          
          # Create symlinks
          cd artifacts/playerctl/usr/lib/aarch64-linux-gnu
          ln -s libplayerctl.so.2.0.0 libplayerctl.so.2
          ln -s libplayerctl.so.2 libplayerctl.so
          cd ../../../../
          
          # Create install script
          cat > artifacts/playerctl/install.sh << 'EOF'
          #!/bin/bash
          
          # Create directories if they don't exist
          sudo mkdir -p /usr/bin
          sudo mkdir -p /usr/lib/aarch64-linux-gnu
          
          # Copy files
          sudo cp usr/bin/playerctl /usr/bin/
          sudo cp -P usr/lib/aarch64-linux-gnu/libplayerctl* /usr/lib/aarch64-linux-gnu/
          
          # Update library cache
          sudo ldconfig
          
          echo "Installation completed. Try running 'playerctl --version'"
          EOF
          
          chmod +x artifacts/playerctl/install.sh
          
          # Create tarball
          cd artifacts
          tar czf playerctl-arm64.tar.gz playerctl/
          
          # Clean up
          docker stop playerctl-build
          docker rm playerctl-build
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: playerctl-arm64
          path: artifacts/playerctl-arm64.tar.gz
          retention-days: 7
