name: Docker Build Playerctl ARM64

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version tag to build (optional)'
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: altdesktop/playerctl
          submodules: recursive
          ref: ${{ github.event.inputs.tag }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build playerctl for ARM64
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/arm64
          push: false
          load: true
          tags: playerctl-arm64:latest
      
      - name: Extract build artifacts
        run: |
          # Create a container from the image
          docker create --name temp playerctl-arm64:latest
          
          # Create directory for artifacts
          mkdir -p artifacts
          
          # List files in container for debugging
          echo "Listing /usr/lib contents:"
          docker exec temp ls -la /usr/lib || true
          echo "Listing /usr/bin contents:"
          docker exec temp ls -la /usr/bin || true
          
          # Copy the built files from the container
          echo "Copying library files..."
          docker cp temp:/usr/lib/x86_64-linux-gnu/libplayerctl.so.2.0.0 artifacts/ || \
          docker cp temp:/usr/lib/aarch64-linux-gnu/libplayerctl.so.2.0.0 artifacts/ || \
          docker cp temp:/usr/lib/libplayerctl.so.2.0.0 artifacts/ || \
          echo "Failed to copy library file"
          
          echo "Copying executable..."
          docker cp temp:/usr/bin/playerctl artifacts/ || \
          echo "Failed to copy executable"
          
          # Create symbolic links
          cd artifacts
          if [ -f "libplayerctl.so.2.0.0" ]; then
            ln -s libplayerctl.so.2.0.0 libplayerctl.so.2
            ln -s libplayerctl.so.2 libplayerctl.so
          fi
          
          # List copied files
          echo "Contents of artifacts directory:"
          ls -la artifacts/
          
          # Clean up container
          docker rm temp
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: playerctl-arm64-build
          path: artifacts/
          retention-days: 7

      - name: Check final artifacts
        run: |
          echo "Final build artifacts:"
          ls -lah artifacts/
