name: Manual Build Playerctl for Armbian

on:
  workflow_dispatch:  # 仅手动触发

jobs:
  build:
    runs-on: ubuntu-20.04  # 使用 Ubuntu 20.04 作为宿主机环境
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 QEMU
        uses: docker/setup-qemu-action@v3

      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 构建 Armbian 适配的 Docker 镜像（基于 ubuntu:20.04）
        run: |
          docker buildx build --platform linux/arm64 -t playerctl-armbian:latest --load --build-arg BASE_IMAGE=ubuntu:20.04 .

      - name: 运行测试
        run: |
          docker run --rm playerctl-armbian:latest bash -c "dbus-daemon --nopidfile --system && dbus-run-session python3 -m pytest -vvs"
