      - name: 1 Build Playerctl for Armbian
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace debian:bookworm \
            bash -c "
            apt update && apt install -y build-essential meson ninja-build pkg-config libglib2.0-dev libdbus-1-dev libgobject-introspection-dev libjson-glib-dev git
            git clone https://github.com/altdesktop/playerctl.git && cd playerctl
            meson build --prefix=/usr && ninja -C build && ninja -C build install
            cp build/playerctl /workspace/playerctl-armbian
            "
