name: Docker Build playerctl for Armbian (ARM64)

on:
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 GitHub 提供的 Ubuntu 环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # 检出代码

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2  # 设置 QEMU 以支持 ARM64 构建

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # 设置 Docker Buildx 以支持多架构构建

      - name: Build ARM64 Docker image
        run: |
          docker buildx create --use
          docker buildx build --platform linux/arm64 -t playerctl-armbian -f Dockerfile .

      - name: Run ARM64 Docker container and compile playerctl
        run: |
          docker run --platform linux/arm64 -v $(pwd):/output playerctl-armbian sh -c "cd /app && meson --prefix=/usr build && ninja -C build && ninja -C build install && cp -r /app/build /output"

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: playerctl-armbian-build
          path: build/
