name: 1 Build playerctl for Armbian

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 安装依赖
      run: |
        sudo apt update
        sudo apt install -y build-essential meson ninja-build \
                            gcc-aarch64-linux-gnu g++-aarch64-linux-gnu \
                            libglib2.0-dev:arm64 libgobject-2.0-dev:arm64 \
                            libgio-2.0-dev:arm64 libdbus-1-dev:arm64 \
                            pkg-config

    - name: 设置 `pkg-config`
      run: |
        export PKG_CONFIG_LIBDIR=/usr/aarch64-linux-gnu/lib/pkgconfig:/usr/aarch64-linux-gnu/share/pkgconfig

    - name: 设置交叉编译环境
      run: |
        echo "[binaries]
        c = 'aarch64-linux-gnu-gcc'
        cpp = 'aarch64-linux-gnu-g++'
        ar = 'aarch64-linux-gnu-ar'
        strip = 'aarch64-linux-gnu-strip'
        pkg-config = 'aarch64-linux-gnu-pkg-config'

        [host_machine]
        system = 'linux'
        cpu_family = 'aarch64'
        cpu = 'armv8-a'
        endian = 'little'" > cross.txt

    - name: 设置编译环境变量
      run: |
        export CFLAGS="-I/usr/aarch64-linux-gnu/include"
        export LDFLAGS="-L/usr/aarch64-linux-gnu/lib"

    - name: 编译 playerctl
      run: |
        meson setup --cross-file=cross.txt -Dintrospection=false build
        cd build
        ninja

    - name: 打包 `.tar.gz`
      run: |
        tar -czvf playerctl-armbian.tar.gz -C build playerctl

    - name: 上传构建产物
      uses: actions/upload-artifact@v4
      with:
        name: playerctl-armbian
        path: playerctl-armbian.tar.gz
